Global seed set to 42
2023-11-15 00:53:40,931	INFO worker.py:1642 -- Started a local Ray instance.
2023-11-15 00:54:04,979	INFO tune.py:228 -- Initializing Ray automatically. For cluster usage or custom Ray initialization, call `ray.init(...)` before `Tuner(...)`.
2023-11-15 00:54:04,997	INFO tune.py:654 -- [output] This will use the new output engine with verbosity 1. To disable the new output and use the legacy output engine, set the environment variable RAY_AIR_NEW_OUTPUT=0. For more information, please see https://github.com/ray-project/ray/issues/36949
2023-11-15 00:54:05,062	WARNING tune.py:997 -- AIR_VERBOSITY is set, ignoring passed-in ProgressReporter for now.
[2m[36m(TorchTrainer pid=1020549)[0m Starting distributed worker processes: ['1021052 (10.6.10.14)']
[2m[36m(RayTrainWorker pid=1021052)[0m Setting up process group for: env:// [rank=0, world_size=1]
[2m[36m(RayTrainWorker pid=1021052)[0m GPU available: True (cuda), used: True
[2m[36m(RayTrainWorker pid=1021052)[0m TPU available: False, using: 0 TPU cores
[2m[36m(RayTrainWorker pid=1021052)[0m IPU available: False, using: 0 IPUs
[2m[36m(RayTrainWorker pid=1021052)[0m HPU available: False, using: 0 HPUs
[2m[36m(_WandbLoggingActor pid=1021047)[0m wandb: Tracking run with wandb version 0.15.10
[2m[36m(_WandbLoggingActor pid=1021047)[0m wandb: W&B syncing is set to `offline` in this directory.  
[2m[36m(_WandbLoggingActor pid=1021047)[0m wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
[2m[36m(RayTrainWorker pid=1021052)[0m /g/data/zk16/zelun/miniconda3/envs/enformer-fine-tune/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py:72: PossibleUserWarning: `max_epochs` was not set. Setting it to 1000 epochs. To train without an epoch limit, set `max_epochs=-1`.
[2m[36m(RayTrainWorker pid=1021052)[0m   rank_zero_warn(
[2m[36m(RayTrainWorker pid=1021052)[0m [rank: 0] Global seed set to 42
[2m[36m(RayTrainWorker pid=1021052)[0m Missing logger folder: /g/data/zk16/zelun/z_li_hon/wonglab_github/enformer-pytorch-fine-tune/ray_results/TorchTrainer_2023-11-15_00-53-33/TorchTrainer_8c552766_1_batch_size=8,cell_type=exe_endo,layer_size=16,lr=0.0321_2023-11-15_00-54-05/lightning_logs
[2m[36m(RayTrainWorker pid=1021052)[0m LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
[2m[36m(RayTrainWorker pid=1021052)[0m 
[2m[36m(RayTrainWorker pid=1021052)[0m   | Name              | Type                   | Params
[2m[36m(RayTrainWorker pid=1021052)[0m -------------------------------------------------------------
[2m[36m(RayTrainWorker pid=1021052)[0m 0 | enformer          | Enformer               | 251 M 
[2m[36m(RayTrainWorker pid=1021052)[0m 1 | model             | BinaryAdapterWrapper   | 257 M 
[2m[36m(RayTrainWorker pid=1021052)[0m 2 | matthews_corrcoef | BinaryMatthewsCorrCoef | 0     
[2m[36m(RayTrainWorker pid=1021052)[0m 3 | f1_score          | BinaryF1Score          | 0     
[2m[36m(RayTrainWorker pid=1021052)[0m 4 | precision         | BinaryPrecision        | 0     
[2m[36m(RayTrainWorker pid=1021052)[0m 5 | recall            | BinaryRecall           | 0     
[2m[36m(RayTrainWorker pid=1021052)[0m 6 | aupr              | BinaryAveragePrecision | 0     
[2m[36m(RayTrainWorker pid=1021052)[0m 7 | cfm               | BinaryConfusionMatrix  | 0     
[2m[36m(RayTrainWorker pid=1021052)[0m 8 | auroc             | BinaryAUROC            | 0     
[2m[36m(RayTrainWorker pid=1021052)[0m -------------------------------------------------------------
[2m[36m(RayTrainWorker pid=1021052)[0m 257 M     Trainable params
[2m[36m(RayTrainWorker pid=1021052)[0m 0         Non-trainable params
[2m[36m(RayTrainWorker pid=1021052)[0m 257 M     Total params
[2m[36m(RayTrainWorker pid=1021052)[0m 1,030.051 Total estimated model params size (MB)
[2m[36m(RayTrainWorker pid=1021052)[0m /g/data/zk16/zelun/miniconda3/envs/enformer-fine-tune/lib/python3.8/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
[2m[36m(RayTrainWorker pid=1021052)[0m   warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
[2m[36m(RayTrainWorker pid=1021052)[0m /g/data/zk16/zelun/miniconda3/envs/enformer-fine-tune/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:43: TorchMetricsUserWarning: You are trying to use a metric in deterministic mode on GPU that uses `torch.cumsum`, which is currently not supported. The tensor will be copied to the CPU memory to compute it and then copied back to GPU. Expect some slowdowns.
[2m[36m(RayTrainWorker pid=1021052)[0m   warnings.warn(*args, **kwargs)  # noqa: B028
[2m[36m(RayTrainWorker pid=1021052)[0m /g/data/zk16/zelun/miniconda3/envs/enformer-fine-tune/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:43: UserWarning: No positive samples in targets, true positive value should be meaningless. Returning zero tensor in true positive score
[2m[36m(RayTrainWorker pid=1021052)[0m   warnings.warn(*args, **kwargs)  # noqa: B028
[2m[36m(RayTrainWorker pid=1021052)[0m finetune/fine_tune_tidy.py:232: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
[2m[36m(RayTrainWorker pid=1021052)[0m   mcc = torch.tensor(self.matthews_corrcoef(probs, targets.int()), dtype=torch.float32)
2023-11-15 00:56:31,489	WARNING bohb_search.py:249 -- BOHB Info not detected in result. Are you using HyperBandForBOHB as a scheduler?
[2m[36m(RayTrainWorker pid=1021052)[0m Checkpoint successfully created at: Checkpoint(filesystem=local, path=/g/data/zk16/zelun/z_li_hon/wonglab_github/enformer-pytorch-fine-tune/ray_results/TorchTrainer_2023-11-15_00-53-33/TorchTrainer_8c552766_1_batch_size=8,cell_type=exe_endo,layer_size=16,lr=0.0321_2023-11-15_00-54-05/checkpoint_000000)
2023-11-15 00:56:35,282	WARNING util.py:315 -- The `callbacks.on_trial_result` operation took 3.792 s, which may be a performance bottleneck.
2023-11-15 00:56:35,283	WARNING util.py:315 -- The `process_trial_result` operation took 3.795 s, which may be a performance bottleneck.
2023-11-15 00:56:35,284	WARNING util.py:315 -- Processing trial results took 3.796 s, which may be a performance bottleneck. Please consider reporting results less frequently to Ray Tune.
2023-11-15 00:56:35,284	WARNING util.py:315 -- The `process_trial_result` operation took 3.796 s, which may be a performance bottleneck.
2023-11-15 00:58:03,967	WARNING bohb_search.py:249 -- BOHB Info not detected in result. Are you using HyperBandForBOHB as a scheduler?
[2m[36m(RayTrainWorker pid=1021052)[0m Checkpoint successfully created at: Checkpoint(filesystem=local, path=/g/data/zk16/zelun/z_li_hon/wonglab_github/enformer-pytorch-fine-tune/ray_results/TorchTrainer_2023-11-15_00-53-33/TorchTrainer_8c552766_1_batch_size=8,cell_type=exe_endo,layer_size=16,lr=0.0321_2023-11-15_00-54-05/checkpoint_000001)
2023-11-15 00:59:24,567	WARNING tune_controller.py:865 -- Trial controller checkpointing failed: [Errno 2] No such file or directory: '/g/data/zk16/zelun/z_li_hon/wonglab_github/enformer-pytorch-fine-tune/ray_results/TorchTrainer_2023-11-15_00-53-33/.tmp_search_generator_ckpt' -> '/g/data/zk16/zelun/z_li_hon/wonglab_github/enformer-pytorch-fine-tune/ray_results/TorchTrainer_2023-11-15_00-53-33/search_gen_state-2023-11-15_00-54-05.json'
Traceback (most recent call last):
  File "finetune/fine_tune_tidy.py", line 364, in <module>
    results = tune_func(num_samples=num_samples)
  File "finetune/fine_tune_tidy.py", line 363, in tune_func
    return tuner.fit()
  File "/g/data/zk16/zelun/miniconda3/envs/enformer-fine-tune/lib/python3.8/site-packages/ray/tune/tuner.py", line 372, in fit
    return self._local_tuner.fit()
  File "/g/data/zk16/zelun/miniconda3/envs/enformer-fine-tune/lib/python3.8/site-packages/ray/tune/impl/tuner_internal.py", line 579, in fit
    analysis = self._fit_internal(trainable, param_space)
  File "/g/data/zk16/zelun/miniconda3/envs/enformer-fine-tune/lib/python3.8/site-packages/ray/tune/impl/tuner_internal.py", line 699, in _fit_internal
    analysis = run(
  File "/g/data/zk16/zelun/miniconda3/envs/enformer-fine-tune/lib/python3.8/site-packages/ray/tune/tune.py", line 1103, in run
    runner.step()
  File "/g/data/zk16/zelun/miniconda3/envs/enformer-fine-tune/lib/python3.8/site-packages/ray/tune/execution/tune_controller.py", line 866, in step
    raise e
  File "/g/data/zk16/zelun/miniconda3/envs/enformer-fine-tune/lib/python3.8/site-packages/ray/tune/execution/tune_controller.py", line 863, in step
    self.checkpoint()
  File "/g/data/zk16/zelun/miniconda3/envs/enformer-fine-tune/lib/python3.8/site-packages/ray/tune/execution/tune_controller.py", line 596, in checkpoint
    self._checkpoint_manager.checkpoint(
  File "/g/data/zk16/zelun/miniconda3/envs/enformer-fine-tune/lib/python3.8/site-packages/ray/tune/execution/experiment_state.py", line 257, in checkpoint
    save_fn()
  File "/g/data/zk16/zelun/miniconda3/envs/enformer-fine-tune/lib/python3.8/site-packages/ray/tune/execution/tune_controller.py", line 483, in save_to_dir
    self._search_alg.save_to_dir(experiment_dir, session_str=self._session_str)
  File "/g/data/zk16/zelun/miniconda3/envs/enformer-fine-tune/lib/python3.8/site-packages/ray/tune/search/search_generator.py", line 193, in save_to_dir
    _atomic_save(
  File "/g/data/zk16/zelun/miniconda3/envs/enformer-fine-tune/lib/python3.8/site-packages/ray/tune/utils/util.py", line 529, in _atomic_save
    os.replace(tmp_search_ckpt_path, os.path.join(checkpoint_dir, file_name))
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/zk16/zelun/z_li_hon/wonglab_github/enformer-pytorch-fine-tune/ray_results/TorchTrainer_2023-11-15_00-53-33/.tmp_search_generator_ckpt' -> '/g/data/zk16/zelun/z_li_hon/wonglab_github/enformer-pytorch-fine-tune/ray_results/TorchTrainer_2023-11-15_00-53-33/search_gen_state-2023-11-15_00-54-05.json'
